langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-8bf22b8896e146cf988c3d61e1d2546c
      model-name: qwen3-max
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-8bf22b8896e146cf988c3d61e1d2546c
      model-name: qwen3-max
      log-requests: true
      log-responses: true


logging:
  level:
    dev:
      langchain4j: info